### ISSUE TITLE
[Présentation générale des labos] Rédaction du script

### ISSUE THREAD

**Issue by parastuffs** [BEAMS-EE/ELECH473#5]

**Comment by parastuffs** [comment]
En reprenant la structure de la présentation de labo, décrire le déroulement des laboratoires.

    Garder la vidéo générique, il n'est donc pas nécessaire de citer le nom des assistants ?
    Expliquer qu'il y a une série d'assignements
    Deux séances de permanence de deux heures par semaine afin de répondre aux questions de manière synchrone, mais aussi disponible sur Teams arrow_right renvoyer vers l'UV pour les détails pratiques.
    On va voir 4 architectures différentes : RISC, TIS, dsPIC, x86

**Comment by KenN7** [comment]
@parastuffs un draft est près, j'enregistre ça dès que j'ai le matos, j'attend ta review sur le draft, au cas où j'aurai oublié qqchose.

**Comment by parastuffs** [comment]
J'avais fait mes remarques en commentaire du commit comme l'issue était clos. Je te les remets ici :


Ça me semble bien.
Tu ne parles pas de la répartition labo/examen, mais ça peut changer d'une année à l'autre.
On mettra les têtes des assistants et leur contact directement sur l'UV, dans une section « contact » par exemple.
Il faudra aussi préciser sur l'UV l'organisation des permanences : durée (2h), lieu (Teams) et date.
Je pense que c'est un bon équilibre infos génériques/détails.

Tu comptes tout faire en face cam ou avec un slide ou l'autre ?

**Comment by KenN7** [comment]
je pensais faire face cam avec quelques illustrations par dessus.
